// cities.js
const cities = [
    'Alaminos',
    'Angeles City',
    'Antipolo',
    'Bacolod',
    'Bacoor',
    'Bago',
    'Baguio',
    'Bais',
    'Balanga',
    'Baliwag',
    'Batac',
    'Batangas City',
    'Bayawan',
    'Baybay',
    'Bayugan',
    'Biñan',
    'Bislig',
    'Bogo',
    'Borongan',
    'Butuan',
    'Cabadbaran',
    'Cabanatuan',
    'Cabuyao',
    'Cadiz',
    'Cagayan de Oro',
    'Calaca',
    'Calamba',
    'Calapan',
    'Calbayog',
    'Caloocan',
    'Candon',
    'Canlaon',
    'Carcar',
    'Carmona',
    'Catbalogan',
    'Cauayan',
    'Cavite City',
    'Cebu City',
    'Cotabato City',
    'Dagupan',
    'Danao',
    'Dapitan',
    'Dasmariñas',
    'Davao City',
    'Digos',
    'Dipolog',
    'Dumaguete',
    'El Salvador',
    'Escalante',
    'Gapan',
    'General Santos',
    'General Trias',
    'Gingoog',
    'Guihulngan',
    'Himamaylan',
    'Ilagan',
    'Iligan',
    'Iloilo City',
    'Imus',
    'Iriga',
    'Isabela',
    'Kabankalan',
    'Kidapawan',
    'Koronadal',
    'La Carlota',
    'Lamitan',
    'Laoag',
    'Lapu-Lapu City',
    'Las Piñas',
    'Legazpi',
    'Ligao',
    'Lipa',
    'Lucena',
    'Maasin',
    'Mabalacat',
    'Makati',
    'Malabon',
    'Malaybalay',
    'Malolos',
    'Mandaluyong',
    'Mandaue',
    'Manila',
    'Marawi',
    'Marikina',
    'Masbate City',
    'Mati',
    'Meycauayan',
    'Muñoz',
    'Muntinlupa',
    'Naga (CamSur)',
    'Naga (Cebu)',
    'Navotas',
    'Olongapo',
    'Ormoc',
    'Oroquieta',
    'Ozamiz',
    'Pagadian',
    'Palayan',
    'Panabo',
    'Parañaque',
    'Pasay',
    'Pasig',
    'Passi',
    'Puerto Princesa',
    'Quezon City',
    'Roxas City',
    'Sagay',
    'Samal',
    'San Carlos (Negros Occidental)',
    'San Carlos (Pangasinan)',
    'San Fernando (La Union)',
    'San Fernando (Pampanga)',
    'San Jose (Antique)',
    'San Jose (Nueva Ecija)',
    'San Juan (Batangas)',
    'San Juan (La Union)',
    'San Pablo',
    'San Pedro',
    'Santa Rosa',
    'Santiago',
    'Silay',
    'Sipalay',
    'Sorsogon City',
    'Sorsogon (Bacon)',
    'Surigao City',
    'Tabaco',
    'Tabuk',
    'Tacloban',
    'Tacurong',
    'Tagaytay',
    'Tagbilaran',
    'Taguig',
    'Tagum',
    'Talisay (Batangas)',
    'Talisay (Cebu)',
    'Tanauan',
    'Tangub',
    'Tanjay',
    'Tarlac City',
    'Tayabas',
    'Toledo',
    'Trece Martires',
    'Tuguegarao',
    'Urdaneta',
    'Valencia (Bukidnon)',
    'Valenzuela',
    'Victorias',
    'Vigan',
    'Zamboanga City',
  ];
  export default cities;
  